# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 493c38811649afb42196a6b6dc0c94ee2ec62e01af778be407f2a37eca58dcc3d640cb571f50fd75e1052c415eff46a580cae071c90dbf1351488d060f1bcfd4

test:
  secret_key_base: 3681e59663256b6e3421fb8d344af6a5f77263b5ad195a31cc300f9636ea282db2a5ffb698b5fef5a6336d896c9f306558e52400b1413b12c6f1ca10521bd882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
